on:
  workflow_call:
    inputs:
      translation_directory:
        description: directory to be passed to pybabel compile --directory=...
        required: false
        type: string

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
      - name: compile .po files
        run: |
          pip install -U babel
          if [[ -f setup.cfg ]] && grep -q "compile_catalog" setup.cfg
          then
            python setup.py compile_catalog
          elif [[ -n "${{inputs.translation_directory}}" ]]
          then
            echo 'pybabel compile --directory=${{inputs.translation_directory}} --use-fuzzy'
            pybabel compile --directory=${{inputs.translation_directory}} --use-fuzzy  # TODO: sanitize input
          fi
      - name: check for compilation
        run: |
          find . -name "*.mo"
