on:
  workflow_call:
    inputs:
      translation_directory:
        default: ""
        description: directory to be passed to pybabel compile --directory=...
        required: false
        type: string

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -U babel build
      - name: compile .po files
        env:
          TRANSLATION_DIRECTORY: ${{inputs.translation_directory}}
        run: |
          if [[ -f setup.cfg ]] && grep -q "compile_catalog" setup.cfg
          then
            python setup.py compile_catalog
          elif [[ -n "$TRANSLATION_DIRECTORY" ]]
          then
            if [[ ! -d "$TRANSLATION_DIRECTORY" ]]
            then
              echo "given translation-directory $TRANSLATION_DIRECTORY does not exist"
              exit 1
            fi
            echo "$TRANSLATION_DIRECTORY"
            pybabel compile --directory="$TRANSLATION_DIRECTORY" --use-fuzzy
          fi
      - name: check for compilation
        run: |
          find . -name "*.mo"
      - name: package would be built here
        run: |
          echo "python -m build"  # use this call backend configured in pyproject.toml rather than hardcoding use of setuptools
      - name: package would be published here
        run: |
          echo "use github-action to publish"
