on:
  workflow_call:
    inputs:
      translation_directory:
        description: directory to be passed to pybabel --directory=...
        required: false
        type: string

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "Hello this is Roger; OVER."
          echo "Received translation-dir is " ${{ inputs.translation_directory }} "; OVER."
