on:
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  build-n-publish:
    uses: ./.github/workflows/called-workflow-test.yml
    with:
      translation_directory: ./workflow_tests/translations/
