on:
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  uv-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true
          python-version: 3.12
      - name: fill cache
        run: |
          uv pip install build babel
